import { Nunito_Sans } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";


const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

// components
import { Navbar } from "@/components";

export const metadata = {
  title: "Product Store",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <link className="rounded-xl" rel="shortcut icon" href={`https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6YRcr3vhk-BTfY9CAaNEeJDBWShYwFViONQ&s`} type="image/x-icon" />
      <body className={nunitoSans.className}>

        <Navbar />
        <main>
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
