import { Nunito_Sans } from "next/font/google";
import "./globals.css";


const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

// components
import { Navbar } from "@/components";

export const metadata = {
  title: "Product Store",
  description: "Generated by create next app",
};

// https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsCV_enrCH2Vb04W5_266pQK2p7QWE_JJsdw&s
// https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEIa2hXssHhCh-Pjx_49DOVIX1nyXqzvg1Zw&s

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link className="rounded-xl" rel="shortcut icon" href={`https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6YRcr3vhk-BTfY9CAaNEeJDBWShYwFViONQ&s`} type="image/x-icon" />
      <body className={nunitoSans.className}>

        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
